# Generated by Django 5.1.4 on 2024-12-20 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Frontend', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='activity_level',
            field=models.CharField(blank=True, choices=[('Sedentary', 'Little or no exercise, sitting most of the day'), ('Lightly Active', 'Light exercise or sports 1-3 days per week'), ('Moderately Active', 'Moderate exercise or sports 3-5 days per week'), ('Very Active', 'Hard exercise or sports 6-7 days per week')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='age',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='gender',
            field=models.CharField(blank=True, choices=[('Male', 'Male'), ('Female', 'Female'), ('Other', 'Other')], max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='weight',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
