# Generated by Django 5.1.4 on 2024-12-21 08:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Frontend', '0003_nutritionanalysis'),
    ]

    operations = [
        migrations.RenameField(
            model_name='nutritionanalysis',
            old_name='food_item',
            new_name='food_name',
        ),
    ]
